### ISSUE TITLE
Build training data for spacy

### ISSUE THREAD

**Issue by sahmed53gsu** [sahmed53gsu/UMLS#2]

**Comment by sahmed53gsu** [comment]
We can do this manually or we can use prodigy

**Comment by kswanjitsu** [comment]
Larry is not in this yet, so cannot tag him, but he needs to run his script to build the dataset for Saadh.
If this is not done by tomorrow, as this blocks Saadh from making model, we will have to extend Saadh's deadline by a day per day this is not complete.
Sorry for that sounding so serious lol, but I kinda like this Zen stuff, not exactly Zen, gives me anxiety, but good anxiety.

**Comment by ldj20** [comment]
Script has been done for a few days, it just needs to be run on the MRREL and MRCONSO file. I can learn how to pull those from AWS but am busy for the day so if someone else can do that it'd be great. The file is called sp_trainer_NER.py in the saturn cloud

**Comment by kswanjitsu** [comment]
Larry and Namrata

See the new sptrainer directory in/to declutter the ~/project/build_NER_hypernymy directory
This is where we will optimize the codes Larry wrote sp_trainer_NER.py and sp_trainer_sub.py
To get an idea of how to do this, see the sp_trainer_daskcudf.ipynb file I started.
