### ISSUE TITLE
Need example of training set - spacy

### ISSUE THREAD

**Issue by sahmed53gsu** [sahmed53gsu/UMLS#5]
Saadh - please login to the SaturnCloud and read the README in the directory: ~/project/build_NER_hypernymy/

Login: swanson.eric.karl@gmail.com
Pass: Z3902lkmj!

**Saadh, I uploaded an output example _from prodigy_ annotated training set.**
_If you want to use prodigy it just accepts sentences as input._ 

**Example of input to prodigy:**
_Sentences containing hypernym pairs can be found in the file in SaturnCloud_
~/project/build_NER_hypernymy/real_hypernym_output.txt

See SaturnCloud ~/project/build_NER_hypernymy/real_hypernym_output.txt

**Resources**:
https://prodi.gy/docs/install
https://prodi.gy/docs/named-entity-recognition
https://spacy.io/usage/training
https://spacy.io/api/cli

**Comment by kswanjitsu** [comment]
Saadh - please login to the SaturnCloud and read the README in the directory: ~/project/build_NER_hypernymy/real_hypernym_output.txt

Login: swanson.eric.karl@gmail.com
Pass: Z3902lkmj!

**Saadh, I uploaded an output example _from prodigy_ annotated training set.**
_If you want to use prodigy it just accepts sentences as input._ 

**Example of input to prodigy:**
_Sentences containing hypernym pairs can be found in the file in SaturnCloud_
~/project/build_NER_hypernymy/real_hypernym_output.txt

See SaturnCloud ~/project/build_NER_hypernymy/real_hypernym_output.txt

**Resources**:
https://prodi.gy/docs/install
https://prodi.gy/docs/named-entity-recognition
https://spacy.io/usage/training
https://spacy.io/api/cli
